In [1]:
a = 6

In [2]:
a = 8

In [3]:
a

8

In [4]:
import numpy as np

In [5]:
#create an iterable
it = [3,6,7,11]

In [6]:
#making a numpy array out of it
np.array(it)

array([ 3,  6,  7, 11])

In [7]:
type(np.array(it))

numpy.ndarray

In [8]:
#you can also provide a dictionary as an iterable
d = {"apple":"red fruit", "mango":"King of fruits"}

In [9]:
np.array(d)

array({'apple': 'red fruit', 'mango': 'King of fruits'}, dtype=object)

In [19]:
#2D-array
twod = np.array([[1,2],[3,4]])
#shape of the array - twod.shape
twod

array([[1, 2],
       [3, 4]])

In [13]:
#if the length of the lists is not same
twod= np.array([[1,2],[3,4,5]])
twod

<ipython-input-13-65bdedf74d75>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  twod= np.array([[1,2],[3,4,5]])


array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [14]:
y = np.array([2,5,6,"7"])

In [16]:
y
#this numpy array will become unicode

array(['2', '5', '6', '7'], dtype='<U11')

In [23]:
list(range(9,16,2))

[9, 11, 13, 15]

In [24]:
np.arange(7,16)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
np.arange(7,16,2)

array([ 7,  9, 11, 13, 15])

In [26]:
#in np.arange(), we can give any datatype we want. In np.array(range()), you can only give numbers.

In [29]:
np.arange(40).reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [30]:
arr1 = np.arange(40)

In [31]:
arr2 = arr1.reshape(8,5)

In [32]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [33]:
arr1[0] = 1000

In [34]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [35]:
#If you change the value using arr1 or you change the value using arr2, you will eventually be changing in the same memory location

In [36]:
#But, please note arr1 and arr2 aren't the same
arr1 is arr2

False